sudo: false
language: ruby
rvm:
  - 2.3.3
  - 2.4.1
addons:
  apt:
    packages:
    - libzmq3-dev
cache:
  - apt
  - bundler
before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version
branches:
  only:
    - master
